apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ad
  template:
    metadata:
      labels:
        app: ad
    spec:
      containers:
      - name: ad
        image: ghcr.io/open-telemetry/demo:latest-ad
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_TRACES_ENDPOINT
          value: "http://otel-collector:4318/v1/traces"
        - name: OTEL_EXPORTER_OTLP_METRICS_ENDPOINT
          value: "http://otel-collector:4318/v1/metrics"
---
apiVersion: v1
kind: Service
metadata:
  name: ad
  namespace: astroshop
spec:
  selector:
    app: ad
  ports:
  - port: 8080