apiVersion: apps/v1
kind: Deployment
metadata:
  name: cart
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cart
  template:
    metadata:
      labels:
        app: cart
    spec:
      containers:
      - name: cart
        image: ghcr.io/open-telemetry/astroshop-cart:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: cart
  namespace: astroshop
spec:
  selector:
    app: cart
  ports:
  - port: 8080
    targetPort: 8080
