apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: checkout
  template:
    metadata:
      labels:
        app: checkout
    spec:
      containers:
      - name: checkout
        image: ghcr.io/open-telemetry/demo:latest-checkout
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318
---
apiVersion: v1
kind: Service
metadata:
  name: checkout
  namespace: astroshop
spec:
  selector:
    app: checkout
  ports:
  - port: 8080