apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: currency
  template:
    metadata:
      labels:
        app: currency
    spec:
      containers:
      - name: currency
        image: ghcr.io/open-telemetry/astroshop-currency:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318
---
apiVersion: v1
kind: Service
metadata:
  name: currency
  namespace: astroshop
spec:
  selector:
    app: currency
  ports:
  - port: 8080