apiVersion: apps/v1
kind: Deployment
metadata:
  name: flagd-ui
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flagd-ui
  template:
    metadata:
      labels:
        app: flagd-ui
    spec:
      containers:
      - name: flagd-ui
        image: ghcr.io/open-telemetry/flagd-ui:latest
        env:
        - name: FLAGD_HOST
          value: flagd
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: flagd-ui
  namespace: astroshop
spec:
  selector:
    app: flagd-ui
  ports:
  - port: 3000
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: flagd-ui
  namespace: astroshop
spec:
  to:
    kind: Service
    name: flagd-ui
  port:
    targetPort: 3000
