apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: ghcr.io/open-telemetry/demo:latest-frontend
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: "http://otel-collector:4318"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: astroshop
spec:
  selector:
    app: frontend
  ports:
  - port: 8080
    targetPort: 8080
