apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-proxy
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-proxy
  template:
    metadata:
      labels:
        app: frontend-proxy
    spec:
      containers:
      - name: frontend-proxy
        # Use the Envoy image built for the demo
        image: ghcr.io/open-telemetry/demo:latest-frontendproxy
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_COLLECTOR_HOST
          value: "otel-collector"        # Collector service
        - name: OTEL_COLLECTOR_PORT
          value: "4318"                  # Standard OTLP HTTP port
        # Pass any additional demo proxy settings here
        - name: FRONTEND_HOST
          value: "frontend"
        - name: FRONTEND_PORT
          value: "8080"
        - name: FEATURE_FLAG_SERVICE_HOST
          value: "flagd"
        - name: FEATURE_FLAG_SERVICE_PORT
          value: "8013"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-proxy
  namespace: astroshop
spec:
  selector:
    app: frontend-proxy
  ports:
  - name: http
    port: 8080
    targetPort: 8080