apiVersion: apps/v1
kind: Deployment
metadata:
  name: load-generator
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: load-generator
  template:
    metadata:
      labels:
        app: load-generator
    spec:
      containers:
      - name: load-generator
        image: ghcr.io/open-telemetry/demo:latest-load-generator
        env:
        - name: FRONTEND_ADDR
          value: frontend:8080
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318