apiVersion: apps/v1
kind: Deployment
metadata:
  name: orders
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orders
  template:
    metadata:
      labels:
        app: orders
    spec:
      containers:
      - name: orders
        image: ghcr.io/open-telemetry/astroshop-orders:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318
---
apiVersion: v1
kind: Service
metadata:
  name: orders
  namespace: astroshop
spec:
  selector:
    app: orders
  ports:
  - port: 8080