apiVersion: apps/v1
kind: Deployment
metadata:
  name: payment
  namespace: astroshop
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payment
  template:
    metadata:
      labels:
        app: payment
    spec:
      containers:
      - name: payment
        image: ghcr.io/open-telemetry/astroshop-payment:latest
        ports:
        - containerPort: 8080
        env:
        - name: OTEL_EXPORTER_OTLP_ENDPOINT
          value: http://otel-collector:4318
---
apiVersion: v1
kind: Service
metadata:
  name: payment
  namespace: astroshop
spec:
  selector:
    app: payment
  ports:
  - port: 8080